package com.smartincident.incidentbackend.enums;

public enum Permission {
    // User management
    CREATE_USER(PermissionCategory.USER_MANAGEMENT),
    UPDATE_USER(PermissionCategory.USER_MANAGEMENT),
    DELETE_USER(PermissionCategory.USER_MANAGEMENT),
    ASSIGN_ROLE(PermissionCategory.USER_MANAGEMENT),
    UPDATE_OWN_PROFILE(PermissionCategory.USER_MANAGEMENT),
    DELETE_OWN_ACCOUNT(PermissionCategory.USER_MANAGEMENT),

    // Incident management
    CREATE_INCIDENT(PermissionCategory.INCIDENT_MANAGEMENT),
    UPDATE_INCIDENT(PermissionCategory.INCIDENT_MANAGEMENT),
    CLOSE_INCIDENT(PermissionCategory.INCIDENT_MANAGEMENT),
    DISPATCH_INCIDENT(PermissionCategory.INCIDENT_MANAGEMENT),
    UPLOAD_EVIDENCE(PermissionCategory.INCIDENT_MANAGEMENT),
    VIEW_RESPONDERS(PermissionCategory.INCIDENT_MANAGEMENT),
    VIEW_OWN_INCIDENTS(PermissionCategory.INCIDENT_MANAGEMENT),
    ESCALATE_INCIDENT(PermissionCategory.INCIDENT_MANAGEMENT),
    VIEW_SLA_METRICS(PermissionCategory.INCIDENT_MANAGEMENT),
    VIEW_SLA_BREACHES(PermissionCategory.INCIDENT_MANAGEMENT),
    MANAGE_AFTER_ACTION(PermissionCategory.INCIDENT_MANAGEMENT),
    SUBMIT_AAR(PermissionCategory.INCIDENT_MANAGEMENT),
    APPROVE_AAR(PermissionCategory.INCIDENT_MANAGEMENT),
    ASSIGN_OFFICER(PermissionCategory.INCIDENT_MANAGEMENT),
    VIEW_PENDING_INCIDENTS(PermissionCategory.INCIDENT_MANAGEMENT),
    MANAGE_DISPATCH_QUEUE(PermissionCategory.INCIDENT_MANAGEMENT),
    VIEW_INVESTIGATION_QUEUE(PermissionCategory.INCIDENT_MANAGEMENT),
    VIEW_OFFICER_INCIDENTS(PermissionCategory.INCIDENT_MANAGEMENT),
    DESIGNATE_COMMANDER(PermissionCategory.INCIDENT_MANAGEMENT),
    STATION_REVIEW_INCIDENT(PermissionCategory.INCIDENT_MANAGEMENT),
    DISPATCHER_REVIEW_INCIDENT(PermissionCategory.INCIDENT_MANAGEMENT),
    DISPATCH_AGENCY(PermissionCategory.INCIDENT_MANAGEMENT),
    SEND_CHAT_MESSAGE(PermissionCategory.INCIDENT_MANAGEMENT),
    MANAGE_CHAT_MESSAGES(PermissionCategory.INCIDENT_MANAGEMENT),
    SUBMIT_AFTER_ACTION_REPORT(PermissionCategory.INCIDENT_MANAGEMENT),
    VIEW_AFTER_ACTION_REPORT(PermissionCategory.INCIDENT_MANAGEMENT),
    MANAGE_AFTER_ACTION_REPORT(PermissionCategory.INCIDENT_MANAGEMENT),

    // Resource management
    MANAGE_VEHICLES(PermissionCategory.RESOURCE_MANAGEMENT),
    VIEW_VEHICLES(PermissionCategory.RESOURCE_MANAGEMENT),
    MANAGE_STATIONS(PermissionCategory.RESOURCE_MANAGEMENT),
    MANAGE_CHECKPOINTS(PermissionCategory.RESOURCE_MANAGEMENT),
    VIEW_CHECKPOINTS(PermissionCategory.RESOURCE_MANAGEMENT),
    MANAGE_SHIFTS(PermissionCategory.RESOURCE_MANAGEMENT),
    TRANSFER_OFFICER(PermissionCategory.RESOURCE_MANAGEMENT),
    VIEW_AVAILABLE_OFFICERS(PermissionCategory.RESOURCE_MANAGEMENT),
    VIEW_STATION_APPOINTMENTS(PermissionCategory.RESOURCE_MANAGEMENT),
    VIEW_OFFICER_APPOINTMENTS(PermissionCategory.RESOURCE_MANAGEMENT),
    MANAGE_POLICE_STATION(PermissionCategory.RESOURCE_MANAGEMENT),
    VIEW_NEARBY_STATIONS(PermissionCategory.RESOURCE_MANAGEMENT),
    MANAGE_GEOFENCES(PermissionCategory.RESOURCE_MANAGEMENT),
    VIEW_LIVE_RESOURCES(PermissionCategory.RESOURCE_MANAGEMENT),
    ESCALATE_RESOURCE(PermissionCategory.RESOURCE_MANAGEMENT),
    MANAGE_OFFICER_SHIFTS(PermissionCategory.RESOURCE_MANAGEMENT),
    VIEW_OWN_OFFICER_SHIFT(PermissionCategory.RESOURCE_MANAGEMENT),
    VIEW_OFFICER_ON_DUTY(PermissionCategory.RESOURCE_MANAGEMENT),
    MANAGE_DEPARTMENTS(PermissionCategory.RESOURCE_MANAGEMENT),
    VIEW_DEPARTMENTS(PermissionCategory.RESOURCE_MANAGEMENT),
    DISPATCH_UNITS(PermissionCategory.RESOURCE_MANAGEMENT),
    DELETE_DISPATCH_CENTER(PermissionCategory.RESOURCE_MANAGEMENT),

    // Administration
    MANAGE_AGENCY(PermissionCategory.ADMINISTRATION),
    VIEW_ANALYTICS(PermissionCategory.ADMINISTRATION),
    VIEW_NATIONAL_ANALYTICS(PermissionCategory.ADMINISTRATION),
    VIEW_AUDIT_LOGS(PermissionCategory.ADMINISTRATION),
    VIEW_DISPATCH_CENTER(PermissionCategory.ADMINISTRATION),
    ASSIGN_DISPATCHER(PermissionCategory.ADMINISTRATION);

    private final PermissionCategory category;

    Permission(PermissionCategory category) {
        this.category = category;
    }

    public PermissionCategory getCategory() {
        return category;
    }
}
